import type { ExamSessionStatus, SectionType } from '@/types/jlptExam'

export const JLPT_EXAM_COPY = {
  pageTitle: 'Đề thi JLPT',
  pageDescription: 'Luyện thi JLPT với các đề thi mô phỏng.',
  searchPlaceholder: 'Tìm kiếm đề thi...',
  allLevels: 'Tất cả trình độ',
  questionsUnit: 'câu',
  sectionsUnit: 'phần',
  minutesUnit: 'phút',
  duration: 'Thời gian',
  emptyExams: 'Chưa có đề thi nào. Hãy quay lại sau.',
  paginationPrev: 'Trước',
  paginationNext: 'Sau',
  paginationPage: 'Trang',

  detailTitle: 'Chi tiết đề thi',
  detailDescription: 'Xem thông tin trước khi bắt đầu làm bài.',
  examInfo: 'Thông tin đề thi',
  sectionsList: 'Danh sách phần thi',
  startExam: 'Bắt đầu làm bài',
  resumeExam: 'Tiếp tục làm bài',
  startConfirmTitle: 'Bắt đầu làm bài?',
  startConfirmMessage: 'Sau khi bắt đầu, thời gian sẽ được tính. Bạn có thể thoát và quay lại tiếp tục.',
  startConfirmAction: 'Bắt đầu',
  startCancelAction: 'Hủy',

  sectionTypeLabels: {
    Moji: 'Chữ / Từ vựng',
    Bunpou: 'Ngữ pháp',
    Dokkai: 'Đọc hiểu',
    Choukai: 'Nghe hiểu',
  } satisfies Record<SectionType, string>,

  sessionTitle: 'Làm bài thi',
  timeRemaining: 'Thời gian còn lại',
  timeExpired: 'Hết giờ',
  questionLabel: 'Câu',
  questionOf: '/',
  answered: 'Đã trả lời',
  unanswered: 'Chưa trả lời',
  submitExam: 'Nộp bài',
  submitConfirmTitle: 'Nộp bài thi?',
  submitConfirmMessage: 'Sau khi nộp bài, bạn không thể chỉnh sửa câu trả lời.',
  submitConfirmUnanswered: 'Bạn còn {count} câu chưa trả lời.',
  submitConfirmAction: 'Nộp bài',
  submitCancelAction: 'Tiếp tục làm',
  exitConfirmTitle: 'Thoát bài thi?',
  exitConfirmMessage: 'Tiến trình làm bài sẽ được lưu. Bạn có thể quay lại tiếp tục.',
  exitConfirmAction: 'Thoát',
  exitCancelAction: 'Tiếp tục',
  autoSaving: 'Đang lưu...',
  autoSaved: 'Đã lưu',
  autoSaveFailed: 'Lưu thất bại',
  questionNav: 'Bảng câu hỏi',
  passageLabel: 'Đoạn văn',
  instructionLabel: 'Hướng dẫn',

  resultTitle: 'Kết quả bài thi',
  resultDescription: 'Xem kết quả chi tiết bài thi JLPT.',
  totalScore: 'Tổng điểm',
  passed: 'Đạt',
  failed: 'Không đạt',
  correctCount: 'Đúng',
  wrongCount: 'Sai',
  unansweredCount: 'Bỏ qua',
  sectionScores: 'Điểm theo phần',
  aiAnalysis: 'Phân tích AI',
  aiAnalysisDescription: 'Tóm tắt điểm yếu, dạng lỗi và hướng ôn tập dựa trên bài thi vừa nộp.',
  aiAnalysisLoading: 'AI đang phân tích bài làm của bạn...',
  aiAnalysisUnavailable: 'Chưa thể tải phân tích AI cho bài thi này.',
  aiSummary: 'Tổng quan',
  aiMistakePatterns: 'Dạng lỗi nổi bật',
  aiRecommendations: 'Gợi ý ôn tập',
  aiQuestionInsights: 'Gợi ý AI theo từng câu',
  aiSectionFocus: 'Điểm cần tập trung theo phần',
  aiStrengths: 'Điểm làm tốt',
  aiWeaknesses: 'Điểm yếu chính',
  aiRecommendedFocus: 'Nên luyện tiếp',
  aiEvidence: 'Dấu hiệu nhận thấy',
  aiAdvice: 'Cách cải thiện',
  aiRootCause: 'Nguyên nhân sai',
  aiReviewTags: 'Nhãn ôn tập',
  aiGeneratedAt: 'Cập nhật',
  aiRetry: 'Tải lại phân tích',
  aiOpenTarget: 'Mở gợi ý',
  aiPriority: 'Ưu tiên',
  aiEstimatedMinutes: 'Thời lượng gợi ý',
  score: 'Điểm',
  maxScore: 'Điểm tối đa',
  passScore: 'Điểm đạt',
  questionReview: 'Chi tiết câu hỏi',
  yourAnswer: 'Đáp án của bạn',
  correctAnswer: 'Đáp án đúng',
  explanation: 'Giải thích',
  noAnswer: 'Chưa trả lời',
  viewResult: 'Xem kết quả',
  backToExams: 'Về danh sách đề',
  retakeExam: 'Làm lại',
  passedMessage: 'Chúc mừng! Bạn đã đạt bài thi này.',
  failedMessage: 'Bạn chưa đạt. Hãy cố gắng lần sau nhé!',
  sectionPassed: 'Đạt',
  sectionFailed: 'Không đạt',

  historyTitle: 'Lịch sử làm bài',
  historyDescription: 'Xem lại kết quả các bài thi đã làm.',
  emptyHistory: 'Chưa có bài thi nào. Hãy bắt đầu làm đề!',
  goToExams: 'Xem đề thi',
  statusLabels: {
    InProgress: 'Đang làm',
    Submitted: 'Đã nộp',
    TimedOut: 'Hết giờ',
  } satisfies Record<ExamSessionStatus, string>,
  allStatuses: 'Tất cả trạng thái',
  continueSession: 'Tiếp tục',
  viewResultAction: 'Xem kết quả',
  scoreLabel: 'điểm',
  notScored: 'Chưa chấm',
  startedAt: 'Bắt đầu',
  submittedAt: 'Nộp bài',
} as const
