export const NAVBAR_COPY = {
  brand: 'Tacho',
  library: 'Thư viện',
  quickLearn: "Học nhanh",
  shadowing: 'Luyện phát âm',
  searchLabel: 'Tìm kiếm',
  notifications: 'Thông báo',
  noNotifications: 'Không có thông báo mới',
  profileMenuAriaLabel: 'Mở menu tài khoản',
  avatarFallbackAlt: 'Người dùng',
  themeSwitchAriaLabel: 'Chuyển giao diện tối hoặc sáng',
  logoutLoading: 'Đang đăng xuất...',
  profileMenu: {
    profile: 'Tài khoản',
    dashboard: 'Dashboard',
    learningSettings: 'Cài đặt học tập mặc định',
    darkMode: 'Giao diện tối',
    logout: 'Đăng xuất',
  },
} as const
