import type { ShadowingLevel } from '@/types/shadowing'

export const SHADOWING_COPY = {
  pageTitle: 'Luyện phát âm Shadowing',
  pageDescription: 'Luyện phát âm tiếng Nhật bằng cách bắt chước người bản xứ.',
  searchPlaceholder: 'Tìm kiếm chủ đề...',
  filterByLevel: 'Lọc theo cấp độ',
  allLevels: 'Tất cả cấp độ',
  officialOnly: 'Chỉ hiển thị chủ đề chính thức',
  emptyTopics: 'Chưa có chủ đề nào. Hãy khám phá các chủ đề chính thức để bắt đầu luyện tập.',
  startPractice: 'Bắt đầu luyện tập',
  continuePractice: 'Tiếp tục luyện tập',
  sentencesCount: 'câu',
  byCreator: 'bởi',
  backToTopics: 'Quay lại danh sách',
  topicInfo: 'Thông tin chủ đề',
  sentencesList: 'Danh sách câu',
  startFromBeginning: 'Bắt đầu từ đầu',
  resumePractice: 'Tiếp tục từ câu gợi ý',
  progressSummary: 'Tiến độ',
  completedSentences: 'câu đã luyện',
  bestScore: 'Điểm cao nhất',
  latestScore: 'Điểm gần nhất',
  practiceTitle: 'Luyện phát âm',
  backToTopic: 'Quay lại chủ đề',
  topicSentenceListHint: 'Chọn câu bạn muốn luyện hoặc bắt đầu theo gợi ý của hệ thống.',
  emptySentences: 'Chủ đề này chưa có câu nào để luyện.',
  sentenceScoreLabel: 'Điểm gần nhất',
  noAudioBadge: 'Thiếu audio mẫu',
  listeningPhase: 'Nghe mẫu',
  listeningTitle: 'Nghe và ghi nhớ nhịp câu',
  listeningDescription: 'Nghe audio mẫu vài lần để nắm nhịp, cao độ và cách ngắt câu trước khi bắt đầu shadowing.',
  readyPhase: 'Chuẩn bị',
  readyTitle: 'Sẵn sàng shadowing',
  readyDescription: 'Khi bắt đầu ghi âm, câu gốc sẽ được ẩn để bạn lặp lại theo trí nhớ và âm thanh vừa nghe.',
  recordingPhase: 'Đang ghi âm',
  recordingTitle: 'Đừng nhìn transcript, hãy bám theo âm thanh',
  recordingDescription: 'Transcript đã được ẩn. Hãy nói theo bằng trí nhớ, nhịp và ngữ điệu của câu mẫu.',
  reviewPhase: 'Nghe lại bản ghi',
  reviewTitle: 'Kiểm tra bản ghi của bạn',
  reviewDescription: 'Nghe lại để quyết định thu lại hay gửi chấm điểm.',
  resultPhase: 'Kết quả',
  resultPanelTitle: 'Assessment result',
  resultPanelDescription: 'Chạm hoặc hover vào từng cụm để xem điểm phát âm chi tiết. Các phần điểm thấp sẽ được làm nổi bật trước.',
  transcriptPanelTitle: 'Reference vs result',
  transcriptPanelDescription: 'So sánh câu gốc với phần hệ thống nhận diện để biết đoạn nào đang phát âm chưa ổn.',
  assessmentOverviewTitle: 'Tổng quan điểm số',
  assessmentTimelineTitle: 'Kết quả theo từng cụm',
  assessmentTimelineDescription: 'Các cụm có điểm thấp được đẩy nổi bật để bạn biết nên sửa ở đâu trước.',
  lowScoreLegend: 'Điểm thấp cần ưu tiên luyện lại',
  mediumScoreLegend: 'Điểm trung bình, cần ổn định thêm',
  highScoreLegend: 'Điểm tốt',
  missingScoreLegend: 'Hệ thống chưa chấm được phần này',
  scoreLegendTitle: 'Chú thích',
  referenceTextLabel: 'Câu gốc',
  recognizedTextLabel: 'Hệ thống nghe được',
  hoverForScore: 'Hover để xem điểm',
  tapForScore: 'Chạm để xem điểm',
  noWordAssessment: 'Chưa có dữ liệu chi tiết cho từng từ trong lần chấm này.',
  overallPronunciation: 'Tổng điểm phát âm',
  overallAssessmentDescription: 'Điểm tổng hợp từ Azure Speech dựa trên độ chính xác, độ trôi chảy, độ hoàn thành và ngữ điệu khi có dữ liệu.',
  wordAccuracyTooltip: 'Điểm của cụm này',
  errorTypeLabel: 'Đánh giá',
  errorTypeNone: 'Phát âm ổn',
  errorTypeInsertion: 'Thừa âm',
  errorTypeOmission: 'Thiếu âm',
  errorTypeMispronunciation: 'Phát âm sai',
  errorTypeUnexpectedBreak: 'Ngắt nhịp chưa tự nhiên',
  errorTypeMonotone: 'Ngữ điệu đơn điệu',
  playAudio: 'Nghe audio mẫu',
  pauseAudio: 'Dừng audio mẫu',
  replayAudio: 'Nghe lại audio mẫu',
  startRecording: 'Bắt đầu shadowing',
  stopRecording: 'Dừng ghi âm',
  recordAgain: 'Thu lại',
  submitRecording: 'Gửi bản thu',
  submittingRecording: 'Đang gửi bản thu...',
  listenToRecording: 'Nghe lại bản ghi',
  hiddenTranscriptTitle: 'Transcript đang được ẩn',
  hiddenTranscriptDescription: 'Đây là phần quan trọng của shadowing. Hãy nghe trong đầu và lặp lại mà không nhìn chữ.',
  retrySentence: 'Luyện lại câu này',
  nextSentence: 'Câu tiếp theo',
  finishPractice: 'Hoàn thành chủ đề',
  recordingStatusIdle: 'Bạn có thể nghe lại audio mẫu hoặc bắt đầu shadowing ngay.',
  recordingStatusActive: 'Đang ghi âm. Hãy nói theo nhịp tự nhiên của câu mẫu.',
  recordingStatusCompleted: 'Đã ghi âm xong. Hãy nghe lại bản ghi của bạn trước khi gửi.',
  microphoneHint: 'Cần cho phép microphone để có thể ghi âm câu trả lời.',
  sampleAudioMissingTitle: 'Câu này chưa có audio mẫu',
  sampleAudioMissingDescription: 'Bạn chưa thể luyện shadowing cho câu này vì thiếu audio gốc để bắt chước.',
  practiceSummaryTitle: 'Trạng thái bài luyện',
  practiceSummarySentence: 'Câu hiện tại',
  practiceSummaryTopic: 'Chủ đề',
  practiceSummaryStep: 'Bước hiện tại',
  yourRecording: 'Bản ghi của bạn',
  pronScore: 'Phát âm',
  accuracyScore: 'Độ chính xác',
  fluencyScore: 'Độ trôi chảy',
  completenessScore: 'Độ hoàn thành',
  prosodyScore: 'Ngữ điệu',
  scoreOutOf: '/100',
  historyTitle: 'Lịch sử luyện tập',
  emptyHistory: 'Chưa có lần luyện tập nào. Hãy bắt đầu luyện tập để xem kết quả.',
  attemptTime: 'Thời gian',
  attemptScore: 'Điểm số',
  viewDetails: 'Xem chi tiết',
  loadTopicsError: 'Không thể tải danh sách chủ đề.',
  loadTopicError: 'Không thể tải thông tin chủ đề.',
  loadProgressError: 'Không thể tải tiến độ.',
  submitAttemptError: 'Không thể gửi bản thu. Vui lòng thử lại.',
  micPermissionDenied: 'Vui lòng cho phép truy cập microphone để luyện tập.',
  audioPlaybackError: 'Không thể phát âm thanh.',
  recordingUnavailable: 'Trình duyệt hiện tại chưa hỗ trợ ghi âm.',
  levelLabels: {
    N1: 'N1',
    N2: 'N2',
    N3: 'N3',
    N4: 'N4',
    N5: 'N5',
  } satisfies Record<ShadowingLevel, string>,
  attemptSubmitted: 'Đã gửi bản thu thành công!',
  practiceCompleted: 'Hoàn thành luyện tập!',
} as const

